### ISSUE TITLE
Add startup tone

### ISSUE THREAD

**Issue by m0vva** [G0WCZ/cwc#32]
It would be good to get some audible and/or visual feedback when cwc-station has started.  Maybe send out an "R" and flash the same on the LED?

**Comment by grasuth** [comment]
Yes!
Also with the slightly updated keepalive, the station gets a response from the reflector, so can tell the reflector is there and connected.  Maybe a connected LED.  or some cw..  "dit-dit dit" maybe (the very old landline morese "is the frequency in use" query/response)

are there two states here:  1/ running/startup . 2/ connected?

**Comment by m0vva** [comment]
Good idea on the connected LED.  I have already added a "status" LED on my Pi hat in preparation!  The LED could be off when there is no connection, flash whilst connecting and be solid when connected.

**Comment by grasuth** [comment]
adding a sepate issue for better LED dynamics (breathing, pulsing stuff)
